Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -16,7 +16,7 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
         with:
-          fetch-depth: 0   # <-- désactive le shallow clone
+          fetch-depth: 0   # désactive le shallow clone
 
       - name: Setup Node.js
         uses: actions/setup-node@v4
@@ -46,3 +46,18 @@ jobs:
         run: sonar-scanner
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+
+      - name: Check SonarCloud Quality Gate status
+        run: |
+          echo "Waiting for SonarCloud to process analysis..."
+          sleep 15
+          STATUS=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" \
+            "https://sonarcloud.io/api/qualitygates/project_status?projectKey=Mariamfrm_angular" \
+            | jq -r '.projectStatus.status')
+
+          echo "SonarCloud Quality Gate status: $STATUS"
+
+          if [ "$STATUS" != "OK" ]; then
+            echo "Quality Gate failed. Failing the job."
+            exit 1
+          fi
